### ISSUE TITLE
Convert the site into a microsite with mkdocs

### ISSUE THREAD

**Issue by dmccreary** [Xilinx/graphanalytics#1]
Create a web user interface using:

1. GitHub Pages
2. mkdocs
3. material

Here is an example: https://www.coderdojotc.org/python/

Here is a sample mkdocs file:

https://github.com/CoderDojoTC/python/blob/master/mkdocs.yml

- Dan

**Comment by jimw567** [comment]
Hi Dan, 

I just published the github-pages for our Graph Analytics product: https://xilinx.github.io/graphanalytics/index.html 

Also we now include a demo using Jupyter notebook: https://github.com/Xilinx/graphanalytics/blob/master/plugin/tigergraph/jupyter-demo/TG_demo.ipynb
